### ISSUE TITLE
Only GET supported on collection

### ISSUE THREAD

**Issue by pencil** [ninech/REST-in-Peace#13]
Currently the documentation reads as follows:

> Currently the four HTTP Verbs GET, POST, PATCH and DELETE are supported.
> There are two sections where you can specify endpoints: resource and collection

However, the `collection` section only supports `get`. Either the ambiguity in the  documentation should be fixed or support for other HTTP verbs should be added to the `collection` section.

**Comment by luxflux** [comment]
Thanks! I updated the documentation. :beers:
